### PR TITLE
Handle GitHub's updated Content Security Policy

### PR DESCRIPTION
**Pull request by doredesign**
It looks like GitHub changed their CSP recently. This extension didn't work for me until I added this code.

### CODE REVIEW

**Comment by thieman** [comment]
Thanks, will take a look

**Comment by SeanKilleen** [comment]
Is there any way I might be able to jump in and test this in a dev environment? Happy to confirm that it works if there's a clear path to do so (would love to be able to use this again in Chrome -- it's a great extension!)

**Comment by thieman** [comment]
LGTM, will cut new releases with this now. 🚀 Thanks!

**Comment by thieman** [comment]
Published as 2.0.3, should be live in Chrome store within 30 minutes.

**Pull request merged**
