### PR TITLE
Update imgur upload route

### PR DESCRIPTION
**Pull request by cbayles**
imgur lists `/upload` as an alternative route for POST, but `/image` as the main one. I was getting the CORB error before, but this fixed it for me.

### CODE REVIEW

**Comment by rodrigomaia17** [comment]
Thank you! Definitely fixed it for me :)

**Comment by ricardovsilva** [comment]
This fixed for me also! This PR already have 8 months, is going to be merged?

**Review by ricardovsilva — APPROVED** [review]

**Comment by ricardovsilva** [comment]
@thieman , plz merge this one!!

selfie-1
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by thieman** [comment]
Wow @ricardovsilva you know exactly how to get my attention.

I'll take a look this weekend and see if this patch works, thanks @cbayles also for providing it

**Comment by thieman** [comment]
@ricardovsilva hey I'm definitely going to get to this still but I just realized if you put some pictures of your dogs in this thread it might be faster?

**Comment by ricardovsilva** [comment]
Charlinho

Lara

Charlinho and Lara

# Dogos helping improve open source

**Comment by cbayles** [comment]
I'll get in on that! 😄 
selfie-1

[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by thieman** [comment]
This has made me realize I should add an incredibly important thread for postin' selfies https://github.com/thieman/github-selfies/issues/101

**Comment by thieman** [comment]
Looks good, lemme just run the integration tests

selfie-4
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

Yup we're all good to go here

**Comment by thieman** [comment]
Alright, this is merged and submitted for review in the Chrome store. Apparently that process has gotten a lot more onerous since I last did this, they made me fill out a lot of supplemental information and they just told me it might take *weeks* to get the update published. It used to only take an hour. Walled gardens suck.

In the meantime, you can always run the extension from source by loading it as an unpacked extension.

**Comment by cbayles** [comment]
Fantastic, thanks for doing that.

**Comment by ricardovsilva** [comment]
Thx to @cbayles and @thieman for that. Specially during the pandemic it helps a lot to interact with guys from work. Ty!

**Pull request merged**
