### PR TITLE
Changed the method of linking back to the github repo

### PR DESCRIPTION
**Pull request by jcox92**
This will make it so the images show up in Slack and there is still a link back to your repo. It will look like this:

selfie-0
[_Github Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by thieman** [comment]
Sorry for taking so long to respond to this one, I've been on vacation. Will take it for a spin in the next day or two, thanks!

**Comment by bhollis** [comment]
Any idea why Slack can't handle an image in a link? I swear it can do it for other sites...

**Comment by jcox92** [comment]
I tried a version with the following markdown (spaces on either side of the URL):
```md
[ ![ selfie-0 ]( http://i.imgur.com/Qc3i2j2.png )]( https://github.com/thieman/github-selfies/ )
```
It worked as far as displaying the picture goes, but the link did not work. You'll see below there is a stray `%7C` at the end of the URL, which is a URL encoded pipe character (`|`). I'm not sure where this is coming from.

image

**Comment by jcox92** [comment]
@thieman bump

**Comment by thieman** [comment]
Ahhhh crap, ok ok looking

**Comment by thieman** [comment]
_Debugging a Race Condition_, selfie on HTML5 canvas, 2016

selfie-1
[_Github Selfies_](https://github.com/thieman/github-selfies/)

**Comment by thieman** [comment]
In terms of actual comments, I'd like to request two changes before we merge this:

1. Please capitalize the H in GitHub
2. Ideally, we would only write the linkback once, even if the user takes multiple selfies.

@bhollis Any objections on aesthetic grounds to merging this? Obviously having the linkback as text isn't as pleasing in the GitHub UI, but I think having the selfies show up in Slack is enough of the fun for most people that the tradeoff is probably worth it.

**Comment by jcox92** [comment]
I made the changes you described. Although I'm now realizing this makes the linkback display _after_ the first picture and before subsequent pictures, which might be a little strange

**Comment by thieman** [comment]
Could always prefix the linkback, but before doing so rewrite any existing linkbacks to empty string?

**Comment by jcox92** [comment]
Yea I like that idea. I went ahead and made that change. Let me know if it looks alright to you.

**Comment by thieman** [comment]
LGTM gonna give Ben a chance to get back

**Comment by thieman** [comment]
Merged and new versions pushed to the stores, sorry this took an eternity to get done. Life, right?

**Comment by bhollis** [comment]
It's fine. I'm still amazed that Slack can't deal with a linked image.

**Pull request merged**
